// entry.js
export { Editor, Extension } from '@tiptap/core'
export { default as StarterKit } from '@tiptap/starter-kit'
export { Placeholder } from '@tiptap/extension-placeholder'
export { TextStyle, FontSize, Color, BackgroundColor, FontFamily } from '@tiptap/extension-text-style'
export { default as TextAlign } from '@tiptap/extension-text-align'
export { default as Image } from '@tiptap/extension-image'
export { Dropcursor } from '@tiptap/extensions'
export { default as Paragraph } from '@tiptap/extension-paragraph'
export { default as Link } from '@tiptap/extension-link'
export { default as Underline } from '@tiptap/extension-underline'
export { default as Highlight } from '@tiptap/extension-highlight'
export { TableKit } from '@tiptap/extension-table'
export { Plugin, PluginKey } from '@tiptap/pm/state'
export { Decoration, DecorationSet } from '@tiptap/pm/view'